services:
  whiskerwatcher:
    container_name: whiskerwatcher
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    volumes:
      - ./db/:/app/db
      - ./apps:/app/apps
      - ./conf:/app/conf
      - ./logs:/app/logs
      - ./templates:/app/templates
      - ./static/images:/app/static/images
      - ./models:/app/models
      - ./.vscode_container:/app/.vscode
      - ./requirements.txt:/app/requirements.txt
      - ./pyproject.toml:/app/pyproject.toml
    ports:
      - "8000-8002:8000-8002" # Whisker-Watcher apps
      - "8553:8554"           # RTSP relay
      - "9001:9001"           # Supervisord
    restart: unless-stopped

  # To convert models put them in the 'models' directory and run, eg:
  # > docker compose --profile yolo2onnx run yolo2onnx /models/yolov5.pt v5
  # > docker compose --profile yolo2onnx run yolo2onnx /models/yolov7.pt v7
  yolo2onnx:
    build:
      context: ./apps/yolo2onnx
      dockerfile: Dockerfile
    image: yolo2onnx
    entrypoint: ["python", "convert.py"]
    volumes:
      - ./models:/models
      - ./yolo2onnx.pip_cache:/root/.cache/pip
    profiles: ["yolo2onnx"] # Don't build unless requested