[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[inet_http_server]
port=0.0.0.0:9001
;username=admin        ; optional
;password=secret       ; optional

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:relay_buffer_server]
command=uvicorn apps.relay_buffer_server.main:app --host 0.0.0.0 --port 8000 ;--reload
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/relay_buffer_server_stdout.log
stderr_logfile=/app/logs/relay_buffer_server_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304

[program:mediamtx]
command=/app/mediamtx /app/conf/mediamtx.yml
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/mediamtx_stdout.log
stderr_logfile=/app/logs/mediamtx_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304


[program:inference_server]
command=uvicorn apps.inference_server.main:app --host 0.0.0.0 --port 8001 ;--reload
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/relay_buffer_server_stdout.log
stderr_logfile=/app/logs/relay_buffer_server_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304