[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[inet_http_server]
port=0.0.0.0:9001
;username=admin        ; optional
;password=secret       ; optional

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:stream_manager]
command=uvicorn apps.stream_manager.main:app --host 0.0.0.0 --port 8000 --reload
directory=/app/
autostart=true
autorestart=true
stdout_logfile=/app/logs/stream_manager_stdout.log
stderr_logfile=/app/logs/stream_manager_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304

[program:mediamtx]
command=/app/mediamtx /app/conf/mediamtx.yml
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/mediamtx_stdout.log
stderr_logfile=/app/logs/mediamtx_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304