[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=appuser
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[inet_http_server]
port=0.0.0.0:9001
;username=admin        ; optional
;password=secret       ; optional

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock


[program:image_tagging_server]
command=uvicorn apps.image_tagging_server.main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/logs/image_tagging_server_stdout.log
stderr_logfile=/logs/image_tagging_server_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304

[program:inference_server]
command=uvicorn apps.inference_server.main:app --host 0.0.0.0 --port 8001
directory=/app
autostart=true
autorestart=true
stdout_logfile=/logs/inference_server_stdout.log
stderr_logfile=/logs/inference_server_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304

[program:tasks_server]
command=uvicorn apps.tasks_server.main:app --host 0.0.0.0 --port 8002
directory=/app
autostart=true
autorestart=true
stdout_logfile=/logs/tasks_server_stdout.log
stderr_logfile=/logs/tasks_server_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304

[program:db_server]
command=uvicorn apps.db_server.main:app --host 0.0.0.0 --port 8003
directory=/app
autostart=true
autorestart=true
stdout_logfile=/logs/db_server_stdout.log
stderr_logfile=/logs/db_server_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304

[program:relay_buffer_server]
command=uvicorn apps.relay_buffer_server.main:app --host 0.0.0.0 --port 8004
directory=/app
autostart=true
autorestart=true
stdout_logfile=/logs/relay_buffer_server_stdout.log
stderr_logfile=/logs/relay_buffer_server_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304

[program:mediamtx]
command=/app/mediamtx /conf/mediamtx.yml
directory=/app
autostart=true
autorestart=true
stdout_logfile=/logs/mediamtx_stdout.log
stderr_logfile=/logs/mediamtx_stderr.log
stdout_logfile_maxbytes=4194304
stderr_logfile_maxbytes=4194304

