"""initial

Revision ID: 70896580cdb5
Revises: 
Create Date: 2026-05-22 18:56:57.993744

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '70896580cdb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_filename'), ['filename'], unique=True)

    op.create_table('labels',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['parent_uuid'], ['labels.uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('sources',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_name'), ['name'], unique=True)

    op.create_table('tags',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sa.Enum('GENERIC', 'SYSTEM', name='tagkind'), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('exclusive_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_configs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marked_for_delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('bboxes',
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['image_uuid'], ['images.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_uuid'], ['labels.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('image_labels',
    sa.Column('image_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('UNCERTAIN', 'PRESENT', 'ABSENT', name='imagelabelstatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_uuid'], ['images.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_uuid'], ['labels.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_uuid', 'label_uuid')
    )
    op.create_table('task_instances',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume_data_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['config_uuid'], ['task_configs.uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('bbox_tags',
    sa.Column('bbox_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bbox_uuid'], ['bboxes.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_uuid'], ['tags.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bbox_uuid', 'tag_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bbox_tags')
    op.drop_table('task_instances')
    op.drop_table('image_labels')
    op.drop_table('bboxes')
    op.drop_table('task_configs')
    op.drop_table('tags')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_name'))

    op.drop_table('sources')
    op.drop_table('labels')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_filename'))

    op.drop_table('images')
    # ### end Alembic commands ###
